application: hurb-web-project
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest